## Imports

In [1]:
%load_ext autoreload
%autoreload 2

import logging
import os

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# import helpers.hmodule as hmodule

# hmodule.install_module_if_not_present(
#     "networkx",
#     use_activate=True,
# )
# hmodule.install_module_if_not_present(
#     "pgmpy",
#     use_activate=True,
# )

In [3]:
import helpers.hnotebook as hnotebo

import msml610_utils as ut
#import L08_04_05_causal_inference_utils as mtl0cireout

ut.config_notebook()

# Initialize logger.
logging.basicConfig(level=logging.INFO)
_LOG = logging.getLogger(__name__)
hnotebo.set_logger_to_print(_LOG)
hnotebo.set_all_loggers_to_print()

pymc is not installed
arviz is not installed
preliz is not installed
sns is not installed

Python 3.12.13
Linux 38584b25ad22 6.12.67-linuxkit #1 SMP Sun Jan 25 02:26:28 UTC 2026 aarch64 GNU/Linux

In [4]:
dir_name = "L08_data"
#!ls $dir_name

out_dir_name = "figures/"

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv(os.path.join(dir_name, "management_training.csv"))
import helpers.hpandas_display as hpanddis

hpanddis.display_df(df)

In [8]:
import helpers.hpandas_stats as hpanstat

hpanstat.explore_dataframe(df)

INFO:helpers.hpandas_stats:stats_df=

                       num_rows zeros [%] nans [%] infs [%] valid [%]
departament_id            10391       0.0      0.0      0.0     100.0
intervention              10391      46.0      0.0      0.0      54.0
engagement_score          10391       0.0      0.0      0.0     100.0
tenure                    10391       0.0      0.0      0.0     100.0
n_of_reports              10391       0.0      0.0      0.0     100.0
gender                    10391       0.0      0.0      0.0     100.0
role                      10391      8.13      0.0      0.0     91.87
last_engagement_score     10391       0.0      0.0      0.0     100.0
department_score          10391       0.0      0.0      0.0     100.0
department_size           10391       0.0      0.0      0.0     100.0

In [ ]:
import statsmodels.formula.api as smf

smf.ols("engagement_score ~ intervention",
        data=df).fit().summary().tables[1]

Aborting 685d9793-43c8-42c4-b242-ccd50dd87c76: execute_request